#!/bin/bash

aur() {
  for i in "$@"; do
    arch-chroot "$TARGET" bash -c "
      cd /tmp
      curl https://aur.archlinux.org/packages/${i:0:2}/$i/$i.tar.gz | tar xz
      cd $i
      makepkg --asroot -si --noconfirm --needed
    "
  done
}

aur cower pacaur
