#!/bin/bash

if [ "$(id -u)" != "0" ]; then
  echo "Run as root."
  exit
fi

cd "$(dirname "${BASH_SOURCE[0]}")"

# TODO: add -c flag for custom configuration file.

### OPTIONS

set -a

. roofix.conf

CRYPTNAME="root$RANDOM"
TARGET="$(mktemp -d)"

set +a

green=$'\033[32;1m'
red=$'\033[31;1m'
cyan=$'\033[36;1m'
reset=$'\033[0m'

if ! ping google.com -c 1 > /dev/null; then
  echo Error: Cannot ping google.
  exit
fi

if [ -f "$DEVICE" ]; then
  export IMAGE="$DEVICE"
  export DEVICE=/dev/loop7
else
  if mount | grep -q "$DEVICE"; then
    echo
    echo "   !!! $DEVICE is mounted"
    echo
    exit
  fi
fi

error=false

rm -f roofix.log

find roofix.d | sort | while read path; do
  spaces=$(dirname "$path" | tr -cd '/' | sed -e 's/\//| /g' -e 's/ $/-/')
  name=$(basename "$path" |
         sed -e 's/^[^A-Za-z]*//' -e 's/_/ /g')
  printf "%-40s" "  $spaces$name"
  if [ -f "$path" ]; then
    echo "==== Running $path ====" >> roofix.log
    if "$path" >> roofix.log 2>&1; then
      echo -ne "${green}PASS$reset"
    else
      echo -ne "${red}FAIL$reset"
      error=true
    fi
  fi
  echo
done

if $error; then
  echo "Errors occured, see roofix.log for details"
fi
