#!/usr/bin/zsh -x

settings="
[legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
background-color='rgb(0,0,0)'
scrollbar-policy='never'
use-theme-colors=false
foreground-color='rgb(255,255,255)'
use-system-font=false
font='Monospace 8'

[legacy]
schema-version=uint32 3
default-show-menubar=false"

echo $settings | dconf load /org/gnome/terminal/
echo $settings | su - $NEW_USER -c 'dconf load /org/gnome/terminal/'
