#!/bin/bash -e

# TODO: make this have at least hd{a,b,c}, sd{a,b,c} in here.
# Default to DEVICE

root="$DEVICE"2
cryptdevice="cryptdevice=${root//\//\/}:$CRYPTNAME"
sed -i -e 's/^\(GRUB_CMDLINE_LINUX\)=""/\1="'"$KERNEL_LINE $cryptdevice"'"/' "$TARGET"/etc/default/grub
echo "GRUB_DISABLE_LINUX_UUID=true" >> "$TARGET"/etc/default/grub
arch-chroot "$TARGET" grub-mkconfig -o /boot/grub/grub.cfg
if [ -n "$IMAGE" ]; then
    arch-chroot "$TARGET" grub-install /dev/loop7
else
    arch-chroot "$TARGET" grub-install "$DEVICE"
fi
arch-chroot "$TARGET" mkdir -p /boot/grub/locale
arch-chroot "$TARGET" cp /usr/share/locale/en@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
