#!/usr/bin/zsh -ex

# CREATE PARTITIONS

if [ $DEVICE '==' /dev/loop7 ]; then
  real_device=$IMAGE
  dd of=$IMAGE bs=1 seek=16G count=0 # may be excessive..
else
  real_device=$DEVICE
fi

echo -e "o\nn\np\n1\n\n+32M\nn\np\n2\n\n\na\n1\nw" | fdisk $real_device

if [ -n "$IMAGE" ]; then
  modprobe -r loop
  modprobe loop max_part=15
  losetup /dev/loop7 $IMAGE
  ln -fs /dev/loop7p1 /dev/loop71
  ln -fs /dev/loop7p2 /dev/loop72
fi

if [ -n "$NO_ENCRYPTION" ]; then
  # simply link to the device
  ln -s ${DEVICE}2 /dev/mapper/$CRYPTNAME
else
  # ENCRYPT+MAP ROOT PARTITION
  read -p "encryption passphrase: " passphrase
  set +x
  echo -n $passphrase | cryptsetup -c aes-cbc-essiv:sha256 --use-random -y luksFormat ${DEVICE}2 -d -
  echo -n $passphrase | cryptsetup luksOpen ${DEVICE}2 $CRYPTNAME -d -
  set -x
fi

# CREATE FILESYSTEMS

mkfs.ext4 ${DEVICE}1
mkfs.ext4 /dev/mapper/$CRYPTNAME

# MOUNT FILESYSTEMS

mount /dev/mapper/$CRYPTNAME $TARGET
mkdir -p $TARGET/boot
mount ${DEVICE}1 $TARGET/boot
