#!/bin/bash -e

# CREATE PARTITIONS

if [ "$DEVICE" == /dev/loop7 ]; then
  real_device="$IMAGE"
else
  real_device="$DEVICE"
fi

echo -e "o\nn\np\n1\n\n+100M\nn\np\n2\n\n\na\n1\nw" | fdisk "$real_device"

if [ -n "$IMAGE" ]; then
  modprobe -r loop
  modprobe loop max_part=15
  losetup /dev/loop7 "$IMAGE"
  ln -s /dev/loop7p1 /dev/loop71
  ln -s /dev/loop7p2 /dev/loop72
fi

# ENCRYPT ROOT PARTITION

! [ -z "$passphrase" ] || { echo "\$passphrase variable not set..." && exit 1 ; }

echo -n "$passphrase" | cryptsetup -c aes-cbc-essiv:sha512 --use-random -y luksFormat "$DEVICE"2 -d -

# MAP ROOT PARTITION

! [ -z "$passphrase" ] || { echo "\$passphrase variable not set..." && exit 1 ; }

echo -n "$passphrase" | cryptsetup luksOpen "$DEVICE"2 "$CRYPTNAME" -d -

# CREATE FILESYSTEMS

mkfs.ext4 "$DEVICE"1
mkfs.ext4 "/dev/mapper/$CRYPTNAME"

# MOUNT FILESYSTEMS

mount "/dev/mapper/$CRYPTNAME" "$TARGET"
mkdir -p "$TARGET/boot"
mount "$DEVICE"1 "$TARGET/boot"
