#!/bin/bash -ex

# Installs the base system packages in $TARGET

# These packages are the *minimum* required to re-roofies.

pacstrap -c -C pacstrap.conf "$TARGET" base syslinux zsh grml-zsh-config p7zip vim git openssh
