#!/usr/bin/zsh

(
  for i in packages/setup/*; do
    j=$(basename $i)
    if { arch-chroot $TARGET pacman -Qi $j || arch-chroot $TARGET pacman -Qg $j ; } >& /dev/null; then
      source $i
    fi
  done
)
