#!/usr/bin/zsh

# TODO: investigate the possibility of doing this all in the original pacstrap

console=(alsa-utils base-devel syslinux arch-install-scripts bc cmake clang gdb
git gnu-netcat googlecl grml-zsh-config iotop irssi john lsof ltrace nasm
nss-mdns ntfs-3g ntp ntop nmap openssh openvpn p7zip python python-pip
python2-crypto python2-pip python2-virtualenv qemu rsync ruby screen subversion
strace scrot tcpdump tor transmission-cli unrar unzip vim w3m wget whois words
wpa_supplicant zsh)

xorg=(dmenu bless evince flashplugin gimp gitg gtk2fontsel hsetroot i3status
i3-wm mplayer pidgin pidgin-otr slim slock surf transmission-gtk xchat xorg
xorg-xinit xpdf xterm firefox chromium ttf-freefont)

# ttf-bitstream-vera ttf-dejavu ttf-freefont ttf-liberation

# No support for AUR or multilib just yet...
# aur=(rxvt-unicode-patched metasploit volatility-svn wireshark-cli
# wireshark-gtk sqlmap gist paxctl vim-gist snort sublime-text tlp sup hub jdk
# intellij-idea-community-edition rar)
#
# opengl=(mesa-libgl glu glxinfo glxgears glew glm glfw)
#
# multilib=(multilib-devel skype xf86-video-intel intel-dri lib32-intel-dri
# libtxc_dxtn lib32-libtxc_dxtn steam)

(
  # prefer binding over pacman -r due to possible issues with setup scripts.
  # better to simulate real environment.
  mount -o bind /var/cache/pacman/pkg $TARGET/var/cache/pacman/pkg
  for package_group in $PACKAGES; do
    run pacman --needed --noconfirm -S ${(P)package_group}
  done
  umount $TARGET/var/cache/pacman/pkg
)

(
  for i in packages/setup/*; do
    j=$(basename $i)
    if { run pacman -Qi $j || run pacman -Qg $j ; } >& /dev/null; then
      source $i
    fi
  done
)
