#!/bin/bash -ex

umount "$TARGET"/boot
umount "$TARGET"

if [ -n "$NO_ENCRYPTION" ]; then
  rm "/dev/mapper/$CRYPTNAME"
else
  cryptsetup luksClose "$CRYPTNAME"
fi

if [ -n "$IMAGE" ]; then
    rm -f /dev/loop7{1,2}
    losetup -d /dev/loop7
fi
