#!/usr/bin/zsh -ex

umount $TARGET/boot

finish() {
  umount $TARGET

  if [ -n "$NO_ENCRYPTION" ]; then
    rm /dev/mapper/$CRYPTNAME
  else
    cryptsetup luksClose $CRYPTNAME
  fi
  if [ -n "$IMAGE" ]; then
    rm -f /dev/loop7{1,2}
    losetup -d /dev/loop7
  fi
}

remap() {
  if [ -n "$IMAGE" ]; then
    losetup /dev/loop7 $IMAGE
    ln -fs /dev/loop7p2 /dev/loop72
  fi
  if [ -n "$NO_ENCRYPTION" ]; then
    ln -s ${DEVICE}2 /dev/mapper/$CRYPTNAME
  else
    echo -n roofix | cryptsetup luksOpen ${DEVICE}2 $CRYPTNAME -d -
  fi
}

if [ -n "$RAMFS" ]; then
  tarball=$(mktemp)
  pushd $TARGET
  tar -cpzf $tarball *
  rm -rf *
  mkdir lost+found
  popd

  # if it's an image file, shrink it.
  if [ -n "$IMAGE" ]; then
    uuid=$(blkid -s UUID -o value /dev/mapper/$CRYPTNAME)
    finish
    tarball_size=$(ls -l $tarball | cut -d' ' -f5)
    truncate -s $((tarball_size + 1024*1024*50)) $IMAGE
    echo -e "d\n2\nn\n\n\n\n\nw\n" | fdisk $IMAGE
    remap
    # recreate filesystem. resizing doesn't work.
    mkfs.ext4 -U $uuid /dev/mapper/$CRYPTNAME
    mount /dev/mapper/$CRYPTNAME $TARGET
  fi

  mv $tarball $TARGET/image
fi

finish

rmdir $TARGET
