#!/bin/bash -ex

success=true

if ! grep -q '^\[multilib]' "$TARGET/etc/pacman.conf"; then
  echo "[multilib]" >> "$TARGET/etc/pacman.conf"
  echo "Include = /etc/pacman.d/mirrorlist" >> "$TARGET/etc/pacman.conf"
fi

arch-chroot "$TARGET" pacman -Syyu

for packages in $PACKAGES; do
  if [ -e "packages/groups/$packages" ]; then
    packages=$(<packages/groups/$packages)
  fi
  { echo ; yes ; } | arch-chroot "$TARGET" pacman -S --needed $packages || success=false
done

$success
