#!/bin/bash -ex

success=true

cd packages/setup

for i in *; do
  if { arch-chroot "$TARGET" pacman -Qi "$i" || arch-chroot "$TARGET" pacman -Qg "$i" ; } > /dev/null 2>&1; then
    ./"$i" || success=false
  fi
done

$success
