#!/bin/bash -e

if [ "$DEVICE" == /dev/loop7 ]; then
  real_device="$IMAGE"
else
  real_device="$DEVICE"
fi

echo -e "o\nn\np\n1\n\n+100M\nn\np\n2\n\n\na\n1\nw" | fdisk "$real_device"

if [ -n "$IMAGE" ]; then
  modprobe -r loop
  modprobe loop max_part=15
  losetup /dev/loop7 "$IMAGE"
  ln -s /dev/loop7p1 /dev/loop71
  ln -s /dev/loop7p2 /dev/loop72
fi
