#!/bin/bash -e


success=true

for packages in $PACKAGES; do
  if [ -e "packages/groups/$packages" ]; then
    packages=$(<packages/groups/$packages)
  fi
  arch-chroot "$TARGET" pacman -S --asroot --needed --noedit --noconfirm $packages || success=false
done

$success
